name: Build React App

on:
  push:
    branches: [ production ]
  # pull_request:
  #   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install frontend dependencies with pnpm
      env:
        REACT_APP_BACKEND_URL: https://backend-heroku.herokuapp.com
      run: |
        cd frontend
        pnpm install

    - name: Build frontend with pnpm
      run: |
        cd frontend
        pnpm run build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages  
        folder: frontend/build 
        token: ${{ secrets.GITHUB_TOKEN }}
